{% set version = "0.1.3" %}

package:
  name: pyhat
  version: {{ version }}

source:
  git_url: https://github.com/USGS-Astrogeology/PyHAT
  git_rev: master

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  skip: True  # [not py3k]

requirements:
  build:
    - python=3
    - setuptools
    - numpy
    - pandas
    - scipy
    - plio
  run:
    - python=3
    - numpy
    - pandas
    - scipy
    - plio

test:
  imports:
    - libpyhat

about:
  home: https://github.com/USGS-Astrogeology/PyHAT
  license: Unlicense
